#!/usr/bin/env python3
"""Covariance-aware held-out PNG response audit for mu2 components."""
import argparse,json
from pathlib import Path
import numpy as np
ap=argparse.ArgumentParser(); ap.add_argument('--root',type=Path,required=True); ap.add_argument('--output',type=Path,required=True); a=ap.parse_args(); root=a.root; s=np.arange(40.,300.1,20.); n=30; hold=slice(70,100); rows={}
for key in ['mu2','mu2_gaussian','mu2_connected']:
 f1=np.load(root/f'results/resolution_clean/connected_LC_p_n64.npz'); fm=np.load(root/f'results/resolution_clean/connected_LC_m_n64.npz'); ap=np.asarray(f1[key],float)[hold]; am=np.asarray(fm[key],float)[hold]; resp=(ap-am)/200.; mean=resp.mean(0); cov=np.cov(resp,rowvar=False,ddof=1)/n; se=np.sqrt(np.maximum(np.diag(cov),0)); inv=np.linalg.pinv(cov,rcond=1e-10); chi=float(mean@inv@mean); d=len(mean); hartlap=(n-d-2)/(n-1) if n>d+2 else None; hchi=chi/hartlap if hartlap else None; pull=mean/np.maximum(se,1e-30); large=s>=120.; rr=mean[large]; cc=cov[np.ix_(large,large)]; chlarge=float(rr@np.linalg.pinv(cc,rcond=1e-10)@rr); dl=int(large.sum()); hlarge=chlarge/((n-dl-2)/(n-1)) if n>dl+2 else None
 rows[key]={'mean_response_per_fNL':mean.tolist(),'std_response_realization':resp.std(0,ddof=1).tolist(),'se_response_mean':se.tolist(),'covariance_response_mean':cov.tolist(),'pull_vs_zero':pull.tolist(),'rms_pull_vs_zero':float(np.sqrt(np.mean(pull*pull))),'chi2_vs_zero':chi,'dof':d,'chi2_dof_vs_zero':chi/d,'hartlap_factor':hartlap,'hartlap_corrected_chi2_dof_vs_zero':(hchi/d if hchi is not None else None),'coverage_abs_pull_le_2':float(np.mean(np.abs(pull)<=2)),'large_scale_s_min':120.,'large_scale_chi2_dof_vs_zero':chlarge/dl,'large_scale_hartlap_corrected_chi2_dof_vs_zero':hlarge/dl if hlarge is not None else None}
out={'status':'PASS','schema':'mu2_png_response_holdout_covariance_v1','s':s.tolist(),'pair_ids':[f'real{i:03d}' for i in range(70,100)],'n_pairs':n,'nodes':{'LC_p_minus_LC_m':rows},'scope':'held-out paired PNG response per fNL for raw, Gaussian, and connected mu2','policy':{'response_formula':'(LC_p-LC_m)/200','same_realization_ids':True,'covariance':'realization covariance divided by n_pairs','hartlap_reported':True,'no_response_fit':True,'production_promotion':False},'warning':'This quantifies measured response significance only; it supplies no analytic halo four-point term and cannot promote a production mean.'}
a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(json.dumps(out,indent=2)+'\n'); print(json.dumps({'status':'PASS','hartlap':rows['mu2']['hartlap_factor'],'rms_pull_vs_zero':{k:round(v['rms_pull_vs_zero'],3) for k,v in rows.items()},'large_scale_hartlap_chi2_dof':{k:v['large_scale_hartlap_corrected_chi2_dof_vs_zero'] for k,v in rows.items()}}))
