#!/usr/bin/env python3
"""Fit disjoint fiducial b1 and Pshot from full-lattice CIC powers."""
import argparse,json
from pathlib import Path
import numpy as np
from scipy.optimize import least_squares

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--power',type=Path,required=True);ap.add_argument('--theory',type=Path,required=True);ap.add_argument('--output',type=Path,required=True);a=ap.parse_args();d=np.load(a.power);kv=np.asarray(d['kvecs']);pmode=np.asarray(d['Pmode'],float);k=np.linalg.norm(kv,axis=1);tab=np.loadtxt(a.theory,comments='#');kt,pm=tab[:,0],tab[:,1];n=int(d['nmesh']);L=float(d['boxsize']);h=L/n;edges=np.arange(0,.3+.005,.005);kc=.5*(edges[:-1]+edges[1:]);idx=np.digitize(k,edges)-1;ok=(idx>=0)&(idx<len(kc))&(k>0);cic=np.sinc(kv[:,0]*h/(2*np.pi))**4*np.sinc(kv[:,1]*h/(2*np.pi))**4*np.sinc(kv[:,2]*h/(2*np.pi))**4;counts=np.bincount(idx[ok],minlength=len(kc));tf=np.bincount(idx[ok],weights=cic[ok],minlength=len(kc))/np.maximum(counts,1);mean=np.array([pmode[:,ok&(idx==i)].mean() if np.any(ok&(idx==i)) else np.nan for i in range(len(kc))]);real=np.array([pmode[:,ok&(idx==i)].mean(1) if np.any(ok&(idx==i)) else np.full(len(pmode),np.nan) for i in range(len(kc))]).T;se=np.nanstd(real,axis=0,ddof=1)/np.sqrt(len(pmode)); pmi=np.interp(kc,kt,pm); rows={}
 for kmax in [.03,.05,.08,.1,.15]:
  mask=np.isfinite(mean)&(kc<=kmax); y=mean[mask]; xpm=pmi[mask]; xt=tf[mask]; C=np.cov(real[:,mask],rowvar=False,ddof=1)/len(pmode); P=np.linalg.pinv(C,rcond=1e-10)
  fun=lambda z:(y-(z[0]**2*xpm*xt+z[1]))/np.sqrt(np.maximum(np.diag(C),1e-30)); fit=least_squares(fun,[2.8,4000.],bounds=([0,0],[6,1e6])); b1,ps=fit.x;res=y-(b1*b1*xpm*xt+ps);chi=float(res@P@res);J=fit.jac;cov=np.linalg.pinv(J.T@J,rcond=1e-10);sig=np.sqrt(np.maximum(np.diag(cov),0)); rows[str(kmax)]={'n_bins':int(mask.sum()),'b1':float(b1),'b1_sigma_linearized':float(sig[0]),'P_shot':float(ps),'P_shot_sigma_linearized':float(sig[1]),'chi2':chi,'dof':int(mask.sum()-2),'chi2_dof':chi/max(int(mask.sum()-2),1),'mean_P_h':y.tolist(),'mean_P_h_se':se[mask].tolist(),'k':kc[mask].tolist(),'cic_transfer':xt.tolist(),'model_P_h':(b1*b1*xpm*xt+ps).tolist(),'ratio_model_over_data':((b1*b1*xpm*xt+ps)/np.maximum(y,1e-30)).tolist()}
 out={'status':'PASS','schema':'disjoint_fiducial_b1_fit_v1','power_source':str(a.power),'theory_source':str(a.theory),'nreal':int(len(pmode)),'realization_block':'fiducial real100-real199','nmesh':n,'boxsize_mpc_h':L,'power_convention':'V/Nmesh^6 |FFT(delta_CIC)|^2; zero mode removed','cic_transfer':'isotropic bin mean of sinc^4 per axis','fits':rows,'comparison':{'training_fiducial_b1_kmax003':2.7340475186190334,'training_fiducial_Pshot_kmax003':5467.76,'independent_input_role':'b1/P_h audit only; no PNG response fit'},'scope':'disjoint Gaussian b1 calibration; no heldout use; no production promotion','policy':{'same_mesh_convention':True,'png_response_fit':False,'heldout_realizations_excluded':True,'production_promotion':False}}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'status':'PASS','nreal':out['nreal'],'b1':{k:round(v['b1'],5) for k,v in rows.items()},'Pshot':{k:round(v['P_shot'],1) for k,v in rows.items()},'chi2_dof':{k:round(v['chi2_dof'],2) for k,v in rows.items()}}))
if __name__=='__main__': main()
