#!/usr/bin/env python3
"""Fast training-only bphi response diagnostic after CIC/shot calibration."""
import argparse,json
from pathlib import Path
import numpy as np
from exact_window import mesh_wavevectors,mu1_discrete

def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--root',type=Path,required=True); ap.add_argument('--output',type=Path,required=True); ap.add_argument('--ntrain',type=int,default=70); ap.add_argument('--b1',type=float,default=2.7413); ap.add_argument('--pshot',type=float,default=5467.76); ap.add_argument('--p',type=float,default=1.12); ap.add_argument('--delta-c',type=float,default=1.686); a=ap.parse_args(); root=a.root
 inp=np.load(root/'inputs/quijote_fiducial_z1_theory_lattice64.npz'); kv=np.asarray(inp['kvecs']); pm=np.asarray(inp['Pm'],float); M=np.asarray(inp['M'],float); km=np.linalg.norm(kv,axis=1); n=64; L=1000.; h=L/n; cic=np.sinc(kv[:,0]*h/(2*np.pi))**4*np.sinc(kv[:,1]*h/(2*np.pi))**4*np.sinc(kv[:,2]*h/(2*np.pi))**4; ss=np.arange(40.,300.1,20.)
 m={node:np.load(root/f'results/power_real_n100_n64/moments_{node}_n64.npz') for node in ('LC_m','LC_p','fiducial')}; resp=(np.asarray(m['LC_p']['mu1'],float)[:a.ntrain]-np.asarray(m['LC_m']['mu1'],float)[:a.ntrain])/200.; mean_resp=resp.mean(0); cov_resp=np.cov(resp,rowvar=False,ddof=1)/len(resp); se_resp=np.sqrt(np.diag(cov_resp))
 # Exact linear response template: [mu1(+100)-mu1(-100)]/200 = bphi * 2*b1*Pm*CIC/M projected.
 template=np.array([mu1_discrete(kv,2*a.b1*pm*cic/np.maximum(np.abs(M),1e-30),float(s),width=20.,boxsize=L,cell=h,nmesh=n,power_convention='mesh') for s in ss]); inv=np.linalg.pinv(cov_resp,rcond=1e-10); bp=float(template@inv@mean_resp/(template@inv@template)); bp_uni=2*a.delta_c*(a.b1-a.p); rows={}
 for node in ('fiducial','LC_m','LC_p'):
  d=np.load(root/f'results/nbody_baseline_v1/nbody_{node}_n64.npz'); dm=np.load(root/f'results/power_real_n100_n64/moments_{node}_n64.npz'); hold=np.arange(a.ntrain,len(d['realization_ids'])); fnl=float(np.asarray(d['fNL']).item()); bh=a.b1+fnl*bp/np.maximum(np.abs(M),1e-30); ph=bh*bh*pm*cic+a.pshot*cic; ph[km==0]=0.; pred=np.array([mu1_discrete(kv,ph,float(s),width=20.,boxsize=L,cell=h,nmesh=n,power_convention='mesh') for s in ss]); z=np.asarray(dm['mu1'],float)[hold]; mean=z.mean(0); cr=np.cov(z,rowvar=False,ddof=1); cm=cr/len(z); se=np.sqrt(np.diag(cm)); r=mean-pred; chi=float(r@np.linalg.pinv(cm,rcond=1e-10)@r); rows[node]={'fNL':fnl,'n_holdout':len(hold),'prediction_mu1':pred.tolist(),'mean_mu1':mean.tolist(),'std_realization':np.sqrt(np.diag(cr)).tolist(),'se_mean':se.tolist(),'chi2_dof':chi/len(r),'hartlap_chi2_dof':chi/len(r)*(len(hold)-len(r)-2)/(len(hold)-1),'rms_pull':float(np.sqrt(np.mean((r/np.maximum(se,1e-30))**2))),'coverage':float(np.mean(np.abs(r/np.maximum(se,1e-30))<=2))}
 out={'status':'PASS','schema':'mu1_training_bphi_response_diagnostic_v2','b1':a.b1,'P_shot':a.pshot,'bphi_training_fit':bp,'bphi_universal_reference':bp_uni,'training_response_chi2':float((mean_resp-bp*template)@inv@(mean_resp-bp*template)),'training_response_mean':mean_resp.tolist(),'training_response_se':se_resp.tolist(),'response_template':template.tolist(),'nodes':rows,'scope':'training LC+/- response-only bphi diagnostic; held-out test; no production calibration','policy':{'train_ids':'real000-real069','holdout_ids':'real070-real099','response_fit_training_only':True,'production_promotion':False,'covariance':'C_realization/n_holdout for heldout mean chi2'}}; a.output.write_text(json.dumps(out,indent=2)+'\n'); print(json.dumps({'status':'PASS','bphi_training_fit':bp,'bphi_universal':bp_uni,'heldout_chi2_dof':{k:round(v['chi2_dof'],2) for k,v in rows.items()},'hartlap':{k:round(v['hartlap_chi2_dof'],2) for k,v in rows.items()}}))
if __name__=='__main__':main()
